name: CraftBook
main: com.sk89q.craftbook.bukkit.CraftBookPlugin
version: "${internalVersion}"
dev-url: https://dev.bukkit.org/projects/craftbook
depend: [WorldEdit]
softdepend: [WorldGuard, ProtocolLib, Vault]
api-version: 1.21.3
commands:
